name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
  EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/s3-file-manager:latest .
        docker push ${{ env.DOCKERHUB_USERNAME }}/s3-file-manager:latest

    - name: Install EB CLI
      run: |
        python3 -m pip install --upgrade pip
        pip install awsebcli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Initialize EB only if needed
      run: |
        if [ ! -d ".elasticbeanstalk" ]; then
          eb init ${{ env.EB_APPLICATION_NAME }} --region ${{ env.AWS_REGION }} --quiet
        else
          echo ".elasticbeanstalk folder exists, skipping eb init"
        fi

    - name: Use EB environment
      run: eb use ${{ env.EB_ENVIRONMENT_NAME }}

    - name: Deploy to Elastic Beanstalk
      run: eb deploy ${{ env.EB_ENVIRONMENT_NAME }}

